### ISSUE TITLE
Unable to start activity

### ISSUE THREAD

**Issue by Afaquejaya** [AgoraIO/RTM#171]
I followed the agora doc step by step by taking one home page in which all buttons added to go to that particular page for **Video call, Voice chat  and RTM (Real time chat)** all works fine but when I click on chat button to go to LoginActivity of RTM page app get crashes.

<img width="932" alt="Screenshot 2022-03-12 235912" src="https://user-images.githubusercontent.com/28558078/158030766-7da1cf8c-1f19-4603-865e-7c849ddf5825.png">

```

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.astroprotips, PID: 30683
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.astroprotips/com.android.astroprotips.ui.Chat.activity.MsgLoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.astroprotips.ui.Chat.rtmtutorial.ChatManager com.android.astroprotips.ui.Chat.rtmtutorial.AGApplication.getChatManager()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.astroprotips.ui.Chat.rtmtutorial.ChatManager com.android.astroprotips.ui.Chat.rtmtutorial.AGApplication.getChatManager()' on a null object reference
        at com.android.astroprotips.ui.Chat.activity.MsgLoginActivity.onCreate(MsgLoginActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        
```

**1.** Code that I used to go to the next activity 
```
//Take user to Chat page
        btnChat.setOnClickListener(v -> {
            Intent intent = new Intent(LoginActivityTCaller.this, MsgLoginActivity.class);
            startActivity(intent);

        });
```

> ( I also declared that activity in my manifest.)

Then the app gets crashed with the above-mentioned issue.
Please help me in to this , I google every scenario that can fix this but don't know why its comming.
@yamasite  @yoreland @plutoless

**Comment by yamasite** [comment]
@plutoless Anyone maintaining this demo?

**Comment by Afaquejaya** [comment]
I had created a project with a different name and after mentioning **AGApplication** in **manifest**
like this 
```
 <application
        android:name=".ui.Chat.rtmtutorial.AGApplication"
.
.
.
```

then it worked for me.
