### ISSUE TITLE
demo project not running

### ISSUE THREAD

**Issue by anu035** [AgoraIO/RTM#52]
I have downloded your project from git hub but it is not running 
please find the following error

E:\agora final demo\RTM-master\Agora-RTM-Tutorial-Web>npm run dev

> onetoonertm@2.8.0 dev E:\agora final demo\RTM-master\Agora-RTM-Tutorial-Web
> cross-env NODE_ENV=development webpack-dev-server --config ./scripts --mode development

 10% building 1/1 modules 0 activei ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from E:\agora final demo\RTM-master\Agora-RTM-Tutorial-Web\scripts\
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)←[39m
←[90m    at onErrorNT (internal/child_process.js:456:16)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:81:21)←[39m
Emitted 'error' event on ChildProcess instance at:
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)←[39m
←[90m    at onErrorNT (internal/child_process.js:456:16)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:81:21)←[39m {
  errno: ←[32m'ENOENT'←[39m,
  code: ←[32m'ENOENT'←[39m,
  syscall: ←[32m'spawn cmd'←[39m,
  path: ←[32m'cmd'←[39m,
  spawnargs: [ ←[32m'/c'←[39m, ←[32m'start'←[39m, ←[32m'""'←[39m, ←[32m'/b'←[39m, ←[32m'http://localhost:8080/'←[39m ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onetoonertm@2.8.0 dev: `cross-env NODE_ENV=development webpack-dev-server --config ./scripts --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the onetoonertm@2.8.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ita\AppData\Roaming\npm-cache\_logs\2020-01-21T06_35_54_755Z-debug.log
the log file is 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle onetoonertm@2.8.0~predev: onetoonertm@2.8.0
6 info lifecycle onetoonertm@2.8.0~dev: onetoonertm@2.8.0
7 verbose lifecycle onetoonertm@2.8.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle onetoonertm@2.8.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\agora final demo\RTM-master\Agora-RTM-Tutorial-Web\node_modules\.bin;C:\Program Files\nodejs;c:\android\sdk\platform-tools;C:\Program Files\nodejs\;c:\android\sdk\platform-tools;C:\Users\ita\AppData\Roaming\npm
9 verbose lifecycle onetoonertm@2.8.0~dev: CWD: E:\agora final demo\RTM-master\Agora-RTM-Tutorial-Web
10 silly lifecycle onetoonertm@2.8.0~dev: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --config ./scripts --mode development'
10 silly lifecycle ]
11 silly lifecycle onetoonertm@2.8.0~dev: Returned: code: 1  signal: null
12 info lifecycle onetoonertm@2.8.0~dev: Failed to exec dev script
13 verbose stack Error: onetoonertm@2.8.0 dev: `cross-env NODE_ENV=development webpack-dev-server --config ./scripts --mode development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid onetoonertm@2.8.0
15 verbose cwd E:\agora final demo\RTM-master\Agora-RTM-Tutorial-Web
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error onetoonertm@2.8.0 dev: `cross-env NODE_ENV=development webpack-dev-server --config ./scripts --mode development`
22 error Exit status 1
23 error Failed at the onetoonertm@2.8.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
please help asap

**Comment by plutoless** [comment]
i did a quick test myself and it's working fine. how do you set up your project?

**Comment by anu035** [comment]
i had downloded project from
https://github.com/AgoraIO/RTM
then i had open project in vs code
then i run npm install
then i run npm dev
then i got this error

**Comment by plutoless** [comment]
what is your node version?

**Comment by plutoless** [comment]
could you pls try deleting your node_modules and try npm install again.

**Comment by anu035** [comment]
i did that 
result of npm install
Testing binary
Binary is fine
npm WARN onetoonertm@2.8.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 898 packages from 475 contributors and audited 11360 packages in 60.23s

2 packages are looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

and then i run npm dev same error comes.

**Comment by anu035** [comment]
> what is your node version?

v12.14.1

**Comment by plutoless** [comment]
i changed my node version to v12.14.1 and it's still working fine. i'm not sure what the difference is.  how about re-recloning the repository and try again?

below's my console output

 10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/zhangqianze/Documents/workspace/RTM/Agora-RTM-Tutorial-Web/scripts/
 11% building 13/14 modules 1 active ...nze/Documents/workspace/RTM/Agora-RTM-Tutorial-Web/src/index.jsBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
 11% building 14/16 modules 2 active /Users/zhangqianze/Documents/workspace/RTM/Agora-RTM-Tutorial-Web/node_modules/webpack-dev-server/client/clients/SockJSClient.jsℹ ｢wdm｣: wait until bundle finished: /
 98% after emitting

 DONE  Compiled successfully in 5063ms                                                                                                                                                                        17:05:24

 I  You application is running here http://localhost:8080

 N  Some additionnal notes to be displayed upon successful compilation
ℹ ｢wdm｣: Hash: d78f5040f39bb83fcae3
Version: webpack 4.37.0
Time: 5063ms
Built at: 2020-01-21 17:05:24
                            Asset      Size  Chunks             Chunk Names
    index.d78f5040f39bb83fcae3.js  2.16 MiB   index  [emitted]  index
index.d78f5040f39bb83fcae3.js.map  2.57 MiB   index  [emitted]  index
                       index.html  3.91 KiB          [emitted]
Entrypoint index = index.d78f5040f39bb83fcae3.js index.d78f5040f39bb83fcae3.js.map
[0] multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./src/index.js 52 bytes {index} [built]
[./node_modules/jquery/dist/jquery.js] 274 KiB {index} [built]
[./node_modules/materialize-css/dist/js/materialize.js] 362 KiB {index} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {index} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 4.29 KiB {index} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {index} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {index} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {index} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {index} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.63 KiB {index} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {index} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {index} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {index} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {index} [built]
[./src/index.js] 8.27 KiB {index} [built]
    + 39 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 4.1 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.

**Comment by anu035** [comment]
which editor you are using i use visual studio code,once i run npm install i got
added 898 packages from 475 contributors and audited 11360 packages in 60.23s

2 packages are looking for funding
run npm fund for details
will this cause any problem
when i run npm fund this result i got,did this cause any problem.

E:\agora final demo\RTM-master\Agora-RTM-Tutorial-Web>npm fund
onetoonertm@2.8.0
`-- copy-webpack-plugin@5.1.1
  +-- type: opencollective
  +-- url: https://opencollective.com/webpack
  `-- p-limit@2.2.2
    `-- url: https://github.com/sponsors/sindresorhus

**Comment by plutoless** [comment]
i think npm fund is for donation?
i don't use an editor, i run it in git bash.
