### ISSUE TITLE
报错：no agora_rtm_sdk in java.library.path

### ISSUE THREAD

**Issue by dume2007** [AgoraIO/RTM#57]
```
[vagrant@localhost Agora-RTM-Tutorial-Java]$ java -cp target/RTM-Client-Demo-1.0-SNAPSHOT.jar -Dsun.boot.library.path=lib/ io.agora.RtmJavaDemo
Exception in thread "main" java.lang.UnsatisfiedLinkError: no agora_rtm_sdk in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at io.agora.common.AgoraServiceJNI.ensureNativeInitialized(AgoraServiceJNI.java:26)
	at io.agora.common.AgoraServiceJNI.<clinit>(AgoraServiceJNI.java:21)
	at io.agora.common.Logging.log(Logging.java:26)
	at io.agora.common.Logging.i(Logging.java:50)
	at io.agora.rtm.internal.RtmClientImpl.initRtmService(RtmClientImpl.java:115)
	at io.agora.rtm.internal.RtmClientImpl.<init>(RtmClientImpl.java:100)
	at io.agora.rtm.internal.RtmManager.createRtmInstance(RtmManager.java:11)
	at io.agora.rtm.RtmClient.createInstance(RtmClient.java:60)
	at io.agora.RtmJavaDemo.init(RtmJavaDemo.java:71)
	at io.agora.RtsmJavaDemo.main(RtmJavaDemo.java:239)
[vagrant@localhost Agora-RTM-Tutorial-Java]$ ls lib/
agora_rtm.jar  agora_rtm_sdk.so  PLACEHOLDER
```

见上图，lib目录下是有agora_rtm_sdk.so的，启动命令也指定了java.library.path，还是找不到？咋回事呢？

**Comment by dume2007** [comment]
Ignore it!

**Comment by kagr25** [comment]
@dume2007 - I am also getting the same error. Please help me how i can solve this.

**Comment by plutoless** [comment]
@kagr25 have you tried placing agora_rtm_sdk to /usr/lib?
